from pymongo import MongoClient

WTF_CSRF_ENABLED = True
SECRET_KEY = 'olaComradeSecret'
DB_NAME = 'gtbaas'

DATABASE = MongoClient()[DB_NAME]
CONTAINERS_COLLECTION = DATABASE.containers
USERS_COLLECTION = DATABASE.users
STATISTIC_COLLECTION = DATABASE.statistic
CONTAINER_LOG_COLLECTION = DATABASE.countainer_log
CONTAINER_PROCESSED_LOG_COLLECTION = DATABASE.countainer_log_processed
CONTAINER_PROCESSED_STATS_COLLECTION = DATABASE.countainer_stats_processed

DEBUG = True

TOOL_SERVER = "g2tbaas.loc"
TOOL_PORT = 8000